### ISSUE TITLE
Error: Fetching /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/tavianator/homebrew-tap failed!

### ISSUE THREAD

**Issue by yermulnik** [tavianator/homebrew-tap#3]
It looks like trunk branch rename resulted in Homebrew breakage:
```
> brew update
Error: Fetching /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/tavianator/homebrew-tap failed!

> cd /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/tavianator/homebrew-tap

> git branch -av
* master                         6622857 bfs: Add missing oniguruma dependency
  remotes/origin/HEAD            -> origin/master
  remotes/origin/main            940180b bfs: Version 2.6
  remotes/origin/master          6622857 bfs: Add missing oniguruma dependency
  remotes/origin/sandbox-setugid e1151fc Try to more clearly illustrate the setugid issue
```
![image](https://user-images.githubusercontent.com/1274789/171507303-7c25d639-b983-4c8c-a192-5ae8ddb506bc.png)

Also reinstallation fails:
```
> brew reinstall tavianator/tap/bfs
==> Downloading https://github.com/tavianator/bfs/archive/2.5.tar.gz
Already downloaded: /home/giermulnik/.cache/Homebrew/downloads/7899a9206174a18275aa34ac0f385f963a25dcbdc419a955f64b4
1ebf0de2f1c--bfs-2.5.tar.gz
==> Reinstalling tavianator/tap/bfs
==> make release all
Last 15 lines from /home/giermulnik/.cache/Homebrew/Logs/bfs/01.make:
gcc-11 -D__EXTENSIONS__ -D_ATFILE_SOURCE -D_BSD_SOURCE -D_DARWIN_C_SOURCE -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64 -D_TIME_BITS=64 -D_GNU_SOURCE -DBFS_VERSION=\"2.5\" -DBFS_WITH_ONIGURUMA=1   -std=c11 -I/home/linuxbrew/.linuxbrew/Cellar/oniguruma/6.9.8/include -g -Wall -Wmissing-declarations -Wshadow -Wsign-compare -Wstrict-prototypes -Wimplicit-fallthrough -O3 -flto -DNDEBUG  -MD -MP -MF xregex.d -c xregex.c -o xregex.o
[…]
gcc-11 -D__EXTENSIONS__ -D_ATFILE_SOURCE -D_BSD_SOURCE -D_DARWIN_C_SOURCE -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64 -D_TIME_BITS=64 -D_GNU_SOURCE -DBFS_VERSION=\"2.5\" -DBFS_WITH_ONIGURUMA=1   -std=c11 -I/home/linuxbrew/.linuxbrew/Cellar/oniguruma/6.9.8/include -g -Wall -Wmissing-declarations -Wshadow -Wsign-compare -Wstrict-prototypes -Wimplicit-fallthrough -O3 -flto -DNDEBUG  -MD -MP -MF tests/trie  -Wl,--as-needed   trie.o tests/trie.o  -L/home/linuxbrew/.linuxbrew/Cellar/oniguruma/6.9.8/lib -lonig -lacl -lattr -lcap -lrt   -o tests/trie
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lacl
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lacl
collect2: error: ld returned 1 exit status
make: *** [Makefile:233: bfs] Error 1
make: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make: *** [Makefile:233: tests/trie] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/tavianator/homebrew-tap/issues
```
Any help appreciated.

```
> head -2 /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
```

**Comment by yermulnik** [comment]
`apt install libacl1-dev/focal` fixed the build and `brew reinstall tavianator/tap/bfs` fixed the issue.

**Comment by yermulnik** [comment]
Might worth to announce trunk name change and post steps to let Homebrew overcome this.

**Comment by tavianator** [comment]
Hmm, I didn't realize Homebrew would break like that on the branch rename.  Not sure what the best thing to do is there, maybe keep a `master` branch around that's a copy of `main`.

The missing dependency on `libacl` seems like a packaging bug, but I'm not sure how to do Linux-only dependencies with Homebrew.

**Comment by tavianator** [comment]
Looks like since https://github.com/Homebrew/brew/pull/10423, `brew tap --repair` would fix it.  Too bad it's not totally automatic.

**Comment by yermulnik** [comment]
Didn't know about `brew tap --repair`, thanks for the hint.

What I meant is maybe add `brew tap --repair` (or `brew reinstall tavianator/tap/bfs`) and `libacl1-dev` required dep into README, so that folks like me can find it quickly? 🤔 

And thank for the great tool by the way 😺

**Comment by yermulnik** [comment]
You pointed out that required dep is already listed in README, though it's hidden by default and is listed as build dep for manual build, which made a confusion for me as I didn't pay attention that installation from Brew involved building it from source 🤷🏻

**Comment by yermulnik** [comment]
> but I'm not sure how to do Linux-only dependencies with Homebrew.

I don't think it's possible with Homebrew since at some (or all) of required deps like `libcap1` are not available via Homebrew but only with system packages, so I'd suggest to add verification check into Brew formulae and put an explicit mention for Linux users into README. Thank you.

**Comment by yermulnik** [comment]
Just found out that `brew reinstall tavianator/tap/bfs` didn't help, whereas `brew tap --repair` worked like a charm 👍🏻

**Comment by tavianator** [comment]
Yeah that's documented on the `bfs` README but not here.  The formula here works out of the box on macOS but I never really thought about using Homebrew on Linux (side note: just curious, why are you using Homebrew on Linux?).

I think it makes sense to add a README here mentioning `brew tap --repair` and the Linux-specific stuff.

**Comment by yermulnik** [comment]
> Yeah that's documented on the `bfs` README but not here. 

Can't find `repair` on the `bfs` README 🤔 

> side note: just curious, why are you using Homebrew on Linux?

It provides plenty of software which is not part of official Linux package management systems. It's not OS/distro/version-specific, so maintainers don't need to pull-request to a plenty of different distros and users don't get frustrated when their OS version misses updates for latest versions of software. It's just yet another option of flexibility =)

**Comment by tavianator** [comment]
> > Yeah that's documented on the `bfs` README but not here.
> 
> Can't find `repair` on the `bfs` README thinking

Sorry, "that" was referring to

> You pointed out that required dep is already listed in README, though it's hidden by default and is listed as build dep for manual build, which made a confusion for me as I didn't pay attention that installation from Brew involved building it from source 🤷🏻
